### ISSUE TITLE
Node.js 12 deprecation warning

### ISSUE THREAD

**Issue by asarkar** [haskell-actions/run-ormolu#21] opened 2023-01-10 18:21 UTC
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: mrkkrp/ormolu-action@v8

https://github.com/asarkar/book-of-monads/actions/runs/3885971697

**Comment by mrkkrp** [comment] 2023-01-16 10:16
This is a duplicate of #19. I have recently released `v9` that uses Node.js 16.

**Closed as completed by mrkkrp** 2023-01-16 10:16 UTC
